services:
  front:
    build:
      context: ./App-Test-Front
      dockerfile: Dockerfile
    ports:
      - 8081:5173
    volumes:
      - ./App-Test-Front:/usr/src/app
    depends_on:
      - back
    networks:
      - app

  back:
    build:
      context: ./App-Test-Back
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_TYPE: ${DB_TYPE}
      PORT: ${PORT}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    ports:
      - 8080:${PORT}
    volumes:
      - ./App-Test-Back:/usr/src/app
    depends_on:
      - mysql
    networks:
      - app

  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app

  adminer:
    image: adminer
    ports:
      - 8000:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - app

volumes:
  mysql-data:

networks:
  app:
