version: "3.1"
services:
  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8000:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
volumes:
  mysql-data:
